name: Hello World Workflow
on: push
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome to GHA
        run: echo Welcome to GitHub Actions!
      - name: Welcome multi line run
        run: |
            echo Welcome one
            echo Welcome two