name: Check AWS Access

on:
  push:
    branches:
      - main

jobs:
  check-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::637423418480:role/github-actions-openid-demo
        role-session-name: githubactions
        aws-region: "us-east-1"

    - name: Verify AWS credentials
      run: aws sts get-caller-identity
