name: Hello World Workflow
on: 
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GLOBAL_APP_ENV: prod
    steps:
      - name: Linting the code
        run: echo ${{ secrets.MY_NAME }}