name: Hello World Workflow
on: 
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names: ["Hari","Pavi"]
    steps:
      - name: Print ${{matrix.names}}
        run: "echo name is ${{matrix.names}}"